// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JugadorLiderServiceClient is the client API for JugadorLiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JugadorLiderServiceClient interface {
	SolicitarUnirce(ctx context.Context, in *InscripcionJugador, opts ...grpc.CallOption) (*Jugador, error)
}

type jugadorLiderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJugadorLiderServiceClient(cc grpc.ClientConnInterface) JugadorLiderServiceClient {
	return &jugadorLiderServiceClient{cc}
}

func (c *jugadorLiderServiceClient) SolicitarUnirce(ctx context.Context, in *InscripcionJugador, opts ...grpc.CallOption) (*Jugador, error) {
	out := new(Jugador)
	err := c.cc.Invoke(ctx, "/JugadorLiderService/SolicitarUnirce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JugadorLiderServiceServer is the server API for JugadorLiderService service.
// All implementations must embed UnimplementedJugadorLiderServiceServer
// for forward compatibility
type JugadorLiderServiceServer interface {
	SolicitarUnirce(context.Context, *InscripcionJugador) (*Jugador, error)
	mustEmbedUnimplementedJugadorLiderServiceServer()
}

// UnimplementedJugadorLiderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJugadorLiderServiceServer struct {
}

func (UnimplementedJugadorLiderServiceServer) SolicitarUnirce(context.Context, *InscripcionJugador) (*Jugador, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarUnirce not implemented")
}
func (UnimplementedJugadorLiderServiceServer) mustEmbedUnimplementedJugadorLiderServiceServer() {}

// UnsafeJugadorLiderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JugadorLiderServiceServer will
// result in compilation errors.
type UnsafeJugadorLiderServiceServer interface {
	mustEmbedUnimplementedJugadorLiderServiceServer()
}

func RegisterJugadorLiderServiceServer(s grpc.ServiceRegistrar, srv JugadorLiderServiceServer) {
	s.RegisterService(&JugadorLiderService_ServiceDesc, srv)
}

func _JugadorLiderService_SolicitarUnirce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InscripcionJugador)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JugadorLiderServiceServer).SolicitarUnirce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JugadorLiderService/SolicitarUnirce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JugadorLiderServiceServer).SolicitarUnirce(ctx, req.(*InscripcionJugador))
	}
	return interceptor(ctx, in, info, handler)
}

// JugadorLiderService_ServiceDesc is the grpc.ServiceDesc for JugadorLiderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JugadorLiderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JugadorLiderService",
	HandlerType: (*JugadorLiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarUnirce",
			Handler:    _JugadorLiderService_SolicitarUnirce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/jugador_lider.proto",
}
