// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pb/lider_nameNode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_lider_nameNode_proto protoreflect.FileDescriptor

var file_pb_lider_nameNode_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x2f, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x62, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x32, 0x47, 0x0a, 0x14, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0d, 0x47, 0x75, 0x61,
	0x72, 0x64, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x11, 0x2e, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x09, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_pb_lider_nameNode_proto_goTypes = []interface{}{
	(*JugadaToDataNode)(nil), // 0: JugadaToDataNode
	(*Response)(nil),         // 1: Response
}
var file_pb_lider_nameNode_proto_depIdxs = []int32{
	0, // 0: LiderNameNodeService.GuardarJugada:input_type -> JugadaToDataNode
	1, // 1: LiderNameNodeService.GuardarJugada:output_type -> Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_lider_nameNode_proto_init() }
func file_pb_lider_nameNode_proto_init() {
	if File_pb_lider_nameNode_proto != nil {
		return
	}
	file_pb_data_nameNode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_lider_nameNode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_lider_nameNode_proto_goTypes,
		DependencyIndexes: file_pb_lider_nameNode_proto_depIdxs,
	}.Build()
	File_pb_lider_nameNode_proto = out.File
	file_pb_lider_nameNode_proto_rawDesc = nil
	file_pb_lider_nameNode_proto_goTypes = nil
	file_pb_lider_nameNode_proto_depIdxs = nil
}
