// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pb/lider_nameNode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JugadorId int32 `protobuf:"varint,2,opt,name=jugadorId,proto3" json:"jugadorId,omitempty"`
	Move      int32 `protobuf:"varint,3,opt,name=move,proto3" json:"move,omitempty"`
	Ronda     int32 `protobuf:"varint,4,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Etapa     int32 `protobuf:"varint,5,opt,name=etapa,proto3" json:"etapa,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lider_nameNode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lider_nameNode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_pb_lider_nameNode_proto_rawDescGZIP(), []int{0}
}

func (x *Jugada) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Jugada) GetJugadorId() int32 {
	if x != nil {
		return x.JugadorId
	}
	return 0
}

func (x *Jugada) GetMove() int32 {
	if x != nil {
		return x.Move
	}
	return 0
}

func (x *Jugada) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *Jugada) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State bool `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lider_nameNode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lider_nameNode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pb_lider_nameNode_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

type Etapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etapa int32 `protobuf:"varint,1,opt,name=etapa,proto3" json:"etapa,omitempty"`
	Ronda int32 `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
}

func (x *Etapa) Reset() {
	*x = Etapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lider_nameNode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Etapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etapa) ProtoMessage() {}

func (x *Etapa) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lider_nameNode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etapa.ProtoReflect.Descriptor instead.
func (*Etapa) Descriptor() ([]byte, []int) {
	return file_pb_lider_nameNode_proto_rawDescGZIP(), []int{2}
}

func (x *Etapa) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

func (x *Etapa) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

var File_pb_lider_nameNode_proto protoreflect.FileDescriptor

var file_pb_lider_nameNode_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x2f, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x06, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x74, 0x61, 0x70, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x74, 0x61, 0x70,
	0x61, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x05, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x74, 0x61, 0x70, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x74, 0x61,
	0x70, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x32, 0x6f, 0x0a, 0x14, 0x4c, 0x69, 0x64, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x25, 0x0a, 0x0d, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x12, 0x07, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x61, 0x64, 0x6f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x4f, 0x6e, 0x65, 0x12, 0x07, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_lider_nameNode_proto_rawDescOnce sync.Once
	file_pb_lider_nameNode_proto_rawDescData = file_pb_lider_nameNode_proto_rawDesc
)

func file_pb_lider_nameNode_proto_rawDescGZIP() []byte {
	file_pb_lider_nameNode_proto_rawDescOnce.Do(func() {
		file_pb_lider_nameNode_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_lider_nameNode_proto_rawDescData)
	})
	return file_pb_lider_nameNode_proto_rawDescData
}

var file_pb_lider_nameNode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_lider_nameNode_proto_goTypes = []interface{}{
	(*Jugada)(nil),   // 0: Jugada
	(*Response)(nil), // 1: Response
	(*Etapa)(nil),    // 2: Etapa
}
var file_pb_lider_nameNode_proto_depIdxs = []int32{
	0, // 0: LiderNameNodeService.GuardarJugada:input_type -> Jugada
	0, // 1: LiderNameNodeService.ResultadoJugadasStageOne:input_type -> Jugada
	1, // 2: LiderNameNodeService.GuardarJugada:output_type -> Response
	1, // 3: LiderNameNodeService.ResultadoJugadasStageOne:output_type -> Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_lider_nameNode_proto_init() }
func file_pb_lider_nameNode_proto_init() {
	if File_pb_lider_nameNode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_lider_nameNode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lider_nameNode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lider_nameNode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Etapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_lider_nameNode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_lider_nameNode_proto_goTypes,
		DependencyIndexes: file_pb_lider_nameNode_proto_depIdxs,
		MessageInfos:      file_pb_lider_nameNode_proto_msgTypes,
	}.Build()
	File_pb_lider_nameNode_proto = out.File
	file_pb_lider_nameNode_proto_rawDesc = nil
	file_pb_lider_nameNode_proto_goTypes = nil
	file_pb_lider_nameNode_proto_depIdxs = nil
}
